---
base_url: <%= ENV.fetch('MIO_URI', 'https://master.dev.nativ-systems.com/api') %>
username: <%= ENV.fetch('MIO_USERNAME', 'masteruser') %>
password: <%= ENV.fetch('MIO_PASSWORD', 'm4st3rus3r') %>
