class Mio
 class Model
   class Workflow
     class Transition < Model
       set_resource :workflowDefinitions

       field :from, String, 'Starting node name'
       field :to, String,'Destination node name'
       field :name, String, 'Transition name, empty string infers autogenerated transition name', ''

       nested true

       def create_hash
         h = {name: "from #{@args.from} to #{@args.to}",
          from: @args.from,
          to: @args.to}
         unless @args.name == ''
            h[:name] = @args.name
         end

         h
       end
     end
   end
 end
end
